name: rnn_projects
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - tensorflow>=2.5.0
  - pandas>=1.3.0
  - numpy>=1.19.5
  - matplotlib>=3.4.0
  - scikit-learn>=0.24.2
  - pip>=21.0.0
  - pip:
    - streamlit>=1.10.0
    - plotly>=5.3.0
    - yfinance>=0.1.63
    - ta>=0.7.0
    - nltk>=3.6.0
    - seaborn>=0.11.0
    - wordcloud>=1.8.0
    - datasets>=1.18.0
