[python]
version = "3.10"

[build]
requirements = "requirements.txt"

[conda]
channels = ["defaults"]
dependencies = [
    "python=3.10",
    "pip",
    {"pip": [
        "tensorflow==2.11.0",
        "streamlit>=1.31.0",
        "numpy>=1.23.5",
        "pandas>=2.2.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "plotly>=5.13.0"
    ]}
]
